version: 2

build:
  os: ubuntu-20.04
  apt_packages:
    - graphviz
  tools:
    python: "miniconda3-4.7"

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

conda:
  environment: conda_environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
