name: hstaxe
channels:
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - python=3
  - make
  - autoconf
  - gsl
  - libtool
  - pkg-config
  - cfitsio
  - automake
  - wcstools
  - wcslib-dev
